-- SQL cau hinh bang user/tai_khoan cho module Cau hinh > User.
-- Chay file nay trong Supabase SQL Editor.

create extension if not exists citext;

create table if not exists public.tai_khoan (
  id bigint generated by default as identity primary key,
  ho_va_ten character varying(255),
  ten_dang_nhap public.citext unique,
  mat_khau text,
  vai_tro text not null default 'user',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.tai_khoan add column if not exists ho_va_ten character varying(255);
alter table public.tai_khoan add column if not exists ten_dang_nhap public.citext;
alter table public.tai_khoan add column if not exists mat_khau text;
alter table public.tai_khoan add column if not exists vai_tro text default 'user';
alter table public.tai_khoan add column if not exists created_at timestamp with time zone default now();
alter table public.tai_khoan add column if not exists updated_at timestamp with time zone default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tai_khoan'
      and column_name = 'ho_ten'
  ) then
    execute 'update public.tai_khoan set ho_va_ten = coalesce(ho_va_ten, ho_ten) where ho_va_ten is null';
  end if;
end $$;

create unique index if not exists idx_tai_khoan_ten_dang_nhap_unique
on public.tai_khoan (ten_dang_nhap);

create index if not exists idx_tai_khoan_vai_tro
on public.tai_khoan (vai_tro);

insert into public.tai_khoan (ho_va_ten, ten_dang_nhap, mat_khau, vai_tro)
values ('Administrator', 'admin', 'admin123', 'admin')
on conflict (ten_dang_nhap) do nothing;

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trigger_tai_khoan_updated_at on public.tai_khoan;
create trigger trigger_tai_khoan_updated_at
before update on public.tai_khoan
for each row execute function public.update_updated_at_column();

drop function if exists public.login_user(public.citext, text);
drop function if exists public.login_user(text, text);

create or replace function public.login_user(p_username text, p_password text)
returns table (
  id text,
  full_name text,
  username text,
  role text
)
language sql
security definer
set search_path = public
as $$
  select
    tk.id::text as id,
    tk.ho_va_ten::text as full_name,
    tk.ten_dang_nhap::text as username,
    tk.vai_tro::text as role
  from public.tai_khoan tk
  where lower(tk.ten_dang_nhap::text) = lower(p_username)
    and tk.mat_khau = p_password
  limit 1;
$$;

drop function if exists public.list_users();

create or replace function public.list_users()
returns table (
  id text,
  full_name text,
  username text,
  role text,
  created_at timestamp with time zone
)
language sql
security definer
set search_path = public
as $$
  select
    tk.id::text as id,
    tk.ho_va_ten::text as full_name,
    tk.ten_dang_nhap::text as username,
    tk.vai_tro::text as role,
    tk.created_at
  from public.tai_khoan tk
  order by tk.created_at desc nulls last, tk.id::text;
$$;

revoke all on function public.login_user(text, text) from public;
revoke all on function public.list_users() from public;
grant execute on function public.login_user(text, text) to anon, authenticated;
grant execute on function public.list_users() to anon, authenticated;

alter table public.tai_khoan enable row level security;

notify pgrst, 'reload schema';
